### ISSUE TITLE
Application.RequestStop() throws ArgumentException "the specified view is not part of the hierarchy of this view"

### ISSUE THREAD

**Issue by AdmiralSnyder** [gui-cs/Terminal.Gui#1558]
Hey, i'm using .net 6 on windows, doing 
```cs
Application.RequestStop();
```
or 
```cs
top.Running = false;
```
results in an ArgumentException, i.e. VS debugger popping up.
am I doing something wrong? I've used the StandaloneExample as guidance and don't do anything funny.

this is the stacktrace:

```
   at Terminal.Gui.View.SetFocus(View view)
   at Terminal.Gui.View.FocusFirst()
   at Terminal.Gui.View.FocusNext()
   at Terminal.Gui.View.set_CanFocus(Boolean value)
   at Terminal.Gui.View.Remove(View view)
   at Terminal.Gui.View.Dispose(Boolean disposing)
   at Terminal.Gui.View.Dispose(Boolean disposing)
   at Terminal.Gui.View.Dispose(Boolean disposing)
   at Terminal.Gui.Responder.Dispose()
   at Terminal.Gui.Application.RunState.Dispose(Boolean disposing)
   at Terminal.Gui.Application.RunState.Dispose()
   at Terminal.Gui.Application.End(RunState runState)
   at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler)
   at Terminal.Gui.Application.Run(Func`2 errorHandler)
   at Program.<Main>$(String[] args) in C:\Users\AGayk\source\repos\AudioControlApp\AudioControlApp\Program.cs:line 36
```

**Comment by tznind** [comment]
Can you share your code? Are you able to reproduce this with a simple program e.g.:


```csharp
Application.Init ();

var btn = new Button ("close");
btn.Clicked += () => Application.RequestStop ();
Application.Top.Add (btn);
Application.Run ();
Application.Shutdown ();
```

**Comment by BDisp** [comment]
This is normally happens if you don't added some view to a superview.

**Comment by BDisp** [comment]
@AdmiralSnyder can you test again the `StandaloneExample` with the current main branch, please.

**Comment by tig** [comment]
Closing as not-repo.

**Comment by BDisp** [comment]
> Closing as not-repo.

Didn't closed. Closing now...

**Comment by AdmiralSnyder** [comment]
Hello, sorry, somehow the notifications for your questions slipped through - i can't repro the issue with current nuget (1.7.2)/net6/StandaloneExample... gonna try it on the initially erroring one later (i think it's on another pc)...
