### ISSUE TITLE
Unit tests fail locally first time run, but succeed subsequent times

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#1618]
**Describe the bug**
I've noticed this a few times in past few weeks. It happened again today after pulling the latest `main` down locally. 

**To Reproduce**

In `Terminal.Gui/` root on local machine:
1. `git pull upstream main`
2. `dotnet test`
3.  `dotnet test`

As shown below the first `dotnet test` fails. The 2nd passes. 

Oddly, this does not reproduce if I do a `dotnet clean` and then `dotnet test`.

```pwsh
┌[charl@TIGGER] [ main ≣]
└[~\s\gui.cs]> git pull upstream main
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 8 (delta 7), reused 4 (delta 4), pack-reused 0
Unpacking objects: 100% (8/8), 1.70 KiB | 36.00 KiB/s, done.
From tig:migueldeicaza/gui.cs
 * branch              main       -> FETCH_HEAD
   56c28f6d..a9a0d176  main       -> upstream/main
Updating 56c28f6d..a9a0d176
Fast-forward
 Terminal.Gui/Core/View.cs       |  15 +++---
 UnitTests/ConsoleDriverTests.cs |   8 ++--
 UnitTests/ViewTests.cs          | 101 ++++++++++++++++++++++++++++++++++++++++
 3 files changed, 110 insertions(+), 14 deletions(-)
┌[charl@TIGGER] [ main ↑1]
└[~\s\gui.cs]> git push
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To tig:tig/gui.cs
   56c28f6d..a9a0d176  main -> main
┌[charl@TIGGER] [ main ≣]
└[~\s\gui.cs]> dotnet test
  Determining projects to restore...
  Restored C:\Users\charlie\s\gui.cs\Example\Example.csproj (in 481 ms).
  Restored C:\Users\charlie\s\gui.cs\UICatalog\UICatalog.csproj (in 481 ms).
  Restored C:\Users\charlie\s\gui.cs\ReactiveExample\ReactiveExample.csproj (in 481 ms).
  Restored C:\Users\charlie\s\gui.cs\Terminal.Gui\Terminal.Gui.csproj (in 481 ms).
  Restored C:\Users\charlie\s\gui.cs\UnitTests\UnitTests.csproj (in 704 ms).
  Terminal.Gui -> C:\Users\charlie\s\gui.cs\Terminal.Gui\bin\Debug\net472\Terminal.Gui.dll
  Terminal.Gui -> C:\Users\charlie\s\gui.cs\Terminal.Gui\bin\Debug\netstandard2.0\Terminal.Gui.dll
  Terminal.Gui -> C:\Users\charlie\s\gui.cs\Terminal.Gui\bin\Debug\net6.0\Terminal.Gui.dll
  UICatalog -> C:\Users\charlie\s\gui.cs\UICatalog\bin\Debug\net6.0\UICatalog.dll
  UnitTests -> C:\Users\charlie\s\gui.cs\UnitTests\bin\Debug\net6.0\UnitTests.dll
Test run for C:\Users\charlie\s\gui.cs\UnitTests\bin\Debug\net6.0\UnitTests.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:14.45]     Terminal.Gui.Core.MainLoopTests.AddTimer_Duplicate_Keys_Not_Allowed [FAIL]
  Failed Terminal.Gui.Core.MainLoopTests.AddTimer_Duplicate_Keys_Not_Allowed [1 ms]
  Error Message:
   System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at Terminal.Gui.MainLoop.RunTimers() in C:\Users\charlie\s\gui.cs\Terminal.Gui\Core\MainLoop.cs:line 180
   at Terminal.Gui.MainLoop.MainIteration() in C:\Users\charlie\s\gui.cs\Terminal.Gui\Core\MainLoop.cs:line 241
   at Terminal.Gui.MainLoop.Run() in C:\Users\charlie\s\gui.cs\Terminal.Gui\Core\MainLoop.cs:line 260
   at Terminal.Gui.Core.MainLoopTests.AddTimer_Duplicate_Keys_Not_Allowed() in C:\Users\charlie\s\gui.cs\UnitTests\MainLoopTests.cs:line 292
--- End of stack trace from previous location ---

Failed!  - Failed:     1, Passed:   636, Skipped:     0, Total:   637, Duration: 9 s - UnitTests.dll (net6.0)
┌[charl@TIGGER] [ main ≣]
└[~\s\gui.cs]> dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
  Terminal.Gui -> C:\Users\charlie\s\gui.cs\Terminal.Gui\bin\Debug\net472\Terminal.Gui.dll
  Terminal.Gui -> C:\Users\charlie\s\gui.cs\Terminal.Gui\bin\Debug\netstandard2.0\Terminal.Gui.dll
  Terminal.Gui -> C:\Users\charlie\s\gui.cs\Terminal.Gui\bin\Debug\net6.0\Terminal.Gui.dll
  UICatalog -> C:\Users\charlie\s\gui.cs\UICatalog\bin\Debug\net6.0\UICatalog.dll
  UnitTests -> C:\Users\charlie\s\gui.cs\UnitTests\bin\Debug\net6.0\UnitTests.dll
Test run for C:\Users\charlie\s\gui.cs\UnitTests\bin\Debug\net6.0\UnitTests.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:   637, Skipped:     0, Total:   637, Duration: 8 s - UnitTests.dll (net6.0)
┌[charl@TIGGER] [ main ≣]
└[~\s\gui.cs]>
```

Note this is the same set of tests that were intermittently failing for @bdisp's PR #1606. But in that case it was w/in the GitHub environment. 

**Desktop (please complete the following information):**
 - OS: Win11
 - dotnet:  6.0.200
 - VS 2022 Version 17.2.0 Preview 1.0

**Comment by BDisp** [comment]
@tig I did as yours instructions and I didn't get unit test errors at first `dotnet run`. The only configuration I have different from your is that I'm using the `VS 2022 Version 17.1.0`.

**Comment by veeman** [comment]
I can confirm this. 
If i run the `Terminal.Gui.Core.MainLoopTests.AddTimer_Duplicate_Keys_Not_Allowed` multiple times several exceptions pop ups.

```c#
  Duration: <1 ms
  Message: 
System.NullReferenceException : Object reference not set to an instance of an object.

  Stack Trace: 
MainLoop.RunTimers() line 180
MainLoop.MainIteration() line 241
MainLoop.Run() line 260
MainLoopTests.AddTimer_Duplicate_Keys_Not_Allowed() line 292
```

```c#
  Duration: <1 ms
  Message: 
System.InvalidOperationException : Collection was modified after the enumerator was instantiated.

  Stack Trace: 
Enumerator.MoveNext()
MainLoop.RunTimers() line 176
MainLoop.MainIteration() line 241
MainLoop.Run() line 260
MainLoopTests.AddTimer_Duplicate_Keys_Not_Allowed() line 292

```

```c#
  Duration: 202 ms
  Message: 
Assert.True() Failure
Expected: True
Actual:   False

  Stack Trace: 
MainLoopTests.AddTimer_Duplicate_Keys_Not_Allowed() line 296
```

Looks like a threading race condition.

- OS: Win10
- dotnet: 6.0.200
- VS 2022 Version 17.1.0

**Comment by veeman** [comment]
I have one more test which fails: `Terminal.Gui.Views.DateFieldTests.KeyBindings_Command`

My system language is set to german; i think something like this should fix it.
```c#
public DateFieldTests ()
{
    CultureInfo.CurrentCulture = CultureInfo.CreateSpecificCulture ("en-US");
}
```

**Comment by tig** [comment]
Related: #1712

**Comment by BDisp** [comment]
I think this is already fixed.

**Comment by tig** [comment]
I think so too, but there are other intermittent failures.  E.g.:

This PR's build/test action is failing:  

https://github.com/gui-cs/Terminal.Gui/runs/7634348534?check_suite_focus=true

<img width="764" alt="image" src="https://user-images.githubusercontent.com/585482/182681659-e2832ecc-51a0-41d2-9a7a-5a5289eba307.png">

**Comment by BDisp** [comment]
Strange, in which environment, Windows or Linux?

**Comment by tig** [comment]
> Strange, in which environment, Windows or Linux?

It's in the github action.

**Comment by BDisp** [comment]
> It's in the github action.

But normally pr's from [dependabot](https://github.com/apps/dependabot) always fails on test.

**Comment by tig** [comment]
> > It's in the github action.
> 
> But normally pr's from [dependabot](https://github.com/apps/dependabot) always fails on test.

Some do. Some don't. I can't stand not knowing why! :-)

**Comment by BDisp** [comment]
> Some do. Some don't. I can't stand not knowing why! :-)

I pulled the pr and I'm also getting fail tests and Ill investigate too.

**Comment by BDisp** [comment]
This version doesn't support null argument, so replaces to this:

```cs
		[Fact]
		[InitShutdown]
		public void Hosting_Two_Vertical_ScrollBarView_Throws_ArgumentException ()
		{
			var top = new Toplevel ();
			var host = new View ();
			top.Add (host);
			var v = new ScrollBarView (host, true);
			var h = new ScrollBarView (host, true);

			Assert.Throws<ArgumentException> (() => v.OtherScrollBarView = h);
			Assert.Throws<ArgumentException> (() => h.OtherScrollBarView = v);
		}

		[Fact]
		[InitShutdown]
		public void Hosting_Two_Horizontal_ScrollBarView_Throws_ArgumentException ()
		{
			var top = new Toplevel ();
			var host = new View ();
			top.Add (host);
			var v = new ScrollBarView (host, false);
			var h = new ScrollBarView (host, false);

			Assert.Throws<ArgumentException> (() => v.OtherScrollBarView = h);
			Assert.Throws<ArgumentException> (() => h.OtherScrollBarView = v);
		}

```

**Comment by tig** [comment]
Still happening, now fairly frequently.

This time:

https://github.com/gui-cs/Terminal.Gui/actions/runs/3060967299/jobs/4940372804#step:6:125

**Comment by BDisp** [comment]
Locally i Windows or Linux it runs without failure. Perhaps increasing the time to avoid timeout?

**Comment by tig** [comment]
> Locally in Windows or Linux it runs without failure. Perhaps increasing the time to avoid timeout?

Maybe, but it sure would be nice to know why it started failing regularly with the latest PRs.

**Comment by BDisp** [comment]
Because of this PR #1997. But the changes are great. Perhaps running many instances generate some racing condition. May be we could locking this unit test until is finished avoiding colliding with another instances?
@montekarlos thoughts, please.

**Comment by BDisp** [comment]
The #2013 is already fixed with the PR #2016.

**Comment by tig** [comment]
Just had this happen again

```
dotnet clean
dotnet test
```

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/585482/190705185-a48e5bb7-affb-4629-9316-6a03ba5164d5.png">

``` 
dotnet test
```

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/585482/190705216-08f5f65f-e038-48d9-ab44-9799fc6c0841.png">

**Comment by BDisp** [comment]
You can't rely on the test now because it's broken.

**Comment by BDisp** [comment]
I think surrounding the `Clipboard.Contents` with a `lock` keyword will avoid overriding his value by another process until is finished.
But I can't submit any PR until the `develop` branch is fixed.
```cs
		[Fact]
		[AutoInitShutdown]
		public void Contents_Gets_From_OS_Clipboard ()
		{
			var clipText = "This is a clipboard unit test to get clipboard from OS.";
			var exit = false;
			var getClipText = "";

			lock (Clipboard.Contents) {
				Application.Iteration += () => {
					if (RuntimeInformation.IsOSPlatform (OSPlatform.Windows)) {
						// using (Process clipExe = new Process {
						// 	StartInfo = new ProcessStartInfo {
						// 		RedirectStandardInput = true,
						// 		FileName = "clip"
						// 	}
						// }) {
						// 	clipExe.Start ();
						// 	clipExe.StandardInput.Write (clipText);
						// 	clipExe.StandardInput.Close ();
						// 	var result = clipExe.WaitForExit (500);
						// 	if (result) {
						// 		clipExe.WaitForExit ();
						// 	}
						// }

						using (Process pwsh = new Process {
							StartInfo = new ProcessStartInfo {
								FileName = "powershell",
								Arguments = $"-command \"Set-Clipboard -Value \\\"{clipText}\\\"\""
							}
						}) {
							pwsh.Start ();
							pwsh.WaitForExit ();
						}
						getClipText = Clipboard.Contents.ToString ();

					} else if (RuntimeInformation.IsOSPlatform (OSPlatform.OSX)) {
						using (Process copy = new Process {
							StartInfo = new ProcessStartInfo {
								RedirectStandardInput = true,
								FileName = "pbcopy"
							}
						}) {
							copy.Start ();
							copy.StandardInput.Write (clipText);
							copy.StandardInput.Close ();
							copy.WaitForExit ();
						}
						getClipText = Clipboard.Contents.ToString ();

					} else if (RuntimeInformation.IsOSPlatform (OSPlatform.Linux)) {
						if (Is_WSL_Platform ()) {
							try {
								using (Process bash = new Process {
									StartInfo = new ProcessStartInfo {
										FileName = "powershell.exe",
										Arguments = $"-noprofile -command \"Set-Clipboard -Value \\\"{clipText}\\\"\""
									}
								}) {
									bash.Start ();
									bash.WaitForExit ();
								}

								//using (Process clipExe = new Process {
								//	StartInfo = new ProcessStartInfo {
								//		RedirectStandardInput = true,
								//		FileName = "clip.exe"
								//	}
								//}) {
								//	clipExe.Start ();
								//	clipExe.StandardInput.Write (clipText);
								//	clipExe.StandardInput.Close ();
								//	clipExe.WaitForExit ();
								//	//var result = clipExe.WaitForExit (500);
								//	//if (result) {
								//	//	clipExe.WaitForExit ();
								//	//}
								//}
							} catch {
								exit = true;
							}
							if (!exit) {
								getClipText = Clipboard.Contents.ToString ();
							}
							Application.RequestStop ();
							return;
						}
						if (exit = xclipExists () == false) {
							// xclip doesn't exist then exit.
							Application.RequestStop ();
							return;
						}

						using (Process bash = new Process {
							StartInfo = new ProcessStartInfo {
								FileName = "bash",
								Arguments = $"-c \"xclip -sel clip -i\"",
								RedirectStandardInput = true,
							}
						}) {
							bash.Start ();
							bash.StandardInput.Write (clipText);
							bash.StandardInput.Close ();
							bash.WaitForExit ();
						}
						if (!exit) {
							getClipText = Clipboard.Contents.ToString ();
						}
					}

					Application.RequestStop ();
				};
			}

			Application.Run ();

			if (!exit) {
				Assert.Equal (clipText, getClipText);
			}
		}

```

**Comment by tig** [comment]
This just happened.

<img width="465" alt="image" src="https://user-images.githubusercontent.com/585482/197296478-f40dcc56-7fd6-48ea-8804-a1ed39e2b4b2.png">

Re-running the failed test resulted in it failing again.

I had to exit VS2022 and restart it, and run the tests again to get them to pass.

Not sure if this is the same issue described above, but seems like it.

**Comment by BDisp** [comment]
Did you already merged the #2082 into your working branch?

**Comment by tig** [comment]
Yes. #2082 was merged into develop and I’m sync’d with develop.

**Comment by BDisp** [comment]
One thing that already happened to me was using the clipboard by copy/past during a tests running and some clipboard test fail. That can corrupt the clipboard tests.

**Comment by tig** [comment]
I've not seen this, except when I'm using the clipboard in another app while tests are running. Closing for now!
