### ISSUE TITLE
TextView InsertText does not respect newlines

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#1987]
**Describe the bug**
Passing `\n` or `\r\n` does not result in TextView rendering a new line.  Despite the `Text` property showing the right values.

**To Reproduce**
```csharp
[Fact]
[InitShutdown]
public void TextView_InsertText_Newline ()
{
var tv  = new TextView{
Width = 10,
Height = 10,
};
tv.InsertText("\naaa\nbbb");
//interestingly this passes
Assert.Equal("\naaa\nbbb",tv.Text);

Application.Top.Add (tv);
Application.Begin (Application.Top);

//this fails
GraphViewTests.AssertDriverContentsAre(
@"
aaa
bbb",output
	);
}
```

Error is:
```
[xUnit.net 00:00:01.21]     Terminal.Gui.Views.TextViewTests.TextView_InsertText_Newline [FAIL]
  Failed Terminal.Gui.Views.TextViewTests.TextView_InsertText_Newline [147 ms]
  Error Message:
   Assert.Equal() Failure
           ↓ (pos 1)
Expected: aaa\nbbb
Actual:   abbb
           ↑ (pos 1)
  Stack Trace:
     at Terminal.Gui.Views.GraphViewTests.AssertDriverContentsAre(String expectedLook, ITestOutputHelper output) in /home/thomas/Terminal.Gui/UnitTests/GraphViewTests.cs:line 131
   at Terminal.Gui.Views.TextViewTests.TextView_InsertText_Newline() in /home/thomas/Terminal.Gui/UnitTests/TextViewTests.cs:line 289
  Standard Output Messages:
 Expected:
 aaa
 bbb
 But Was:
 abbb



Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: < 1 ms - /home/thomas/Terminal.Gui/UnitTests/bin/Debug/net6.0/UnitTests.dll (net6.0)

```

**Comment by BDisp** [comment]
> ```cs
> //interestingly this passes
> Assert.Equal("\naaa\nbbb",tv.Text);
> ```

Of course this only passes on `Unix` not on `Windows` :-)
