### ISSUE TITLE
Full screen and restore crashes under circumstances

### ISSUE THREAD

**Issue by chr1st0scli** [gui-cs/Terminal.Gui#2856]
**Describe the bug**
Under certain circumstances, as described in the steps to reproduce below, if you maximize the window and the restore it, the application crashes with an exception in Terminal.Gui.dll with the message "_No process is on the other end of the pipe._"

**To Reproduce**
1. You can use this [repo](https://github.com/chr1st0scli/RainLispConsole) for convenience.
2. Run it and press 2 to enter the terminal gui mode.
3. Type in the TextView, 1 to 14, each on a separate line.
4. Maximize (full screen) the window by clicking the respective icon on the window's title bar.
5. Restore the window by clicking the respective icon on the window's title bar.
6. The exception occurs.

**Expected behavior**
To have the window restored with no problems.

**Screenshots**
![FullScreenAndRestore](https://github.com/gui-cs/Terminal.Gui/assets/5046010/d1253b0a-8ee6-4be3-a3c1-36e21af857e8)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
For what it's worth, this bug hasn't been introduced recently, I had seen it in older versions.

Also, it might not be reproducible in slightly different circumstances. For example, if I count 1 to 10 instead of 14, it does not reproduce. Also, if I make an additional interaction with the TextView, e.g. move the cursor in the middle of the lines, it will also not reproduce! I hope it does not also depend on screen resolution, so that you can easily reproduce it. But in case it is, I am running on 1920 x 1080.

Stack Trace:
```  
   at Terminal.Gui.WindowsConsole.SetConsoleWindow(Int16 cols, Int16 rows)
   at Terminal.Gui.WindowsDriver.ChangeWin(Size e)
   at Terminal.Gui.WindowsMainLoop.Terminal.Gui.IMainLoopDriver.MainIteration()
   at Terminal.Gui.MainLoop.MainIteration()
   at Terminal.Gui.Application.RunMainLoopIteration(RunState& state, Boolean wait, Boolean& firstIteration)
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
   at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler)
   at RainLispConsole.CodeEditor.Run() in C:\Users\gc3ad\source\repos\RainLispConsole\RainLispConsole\CodeEditor.cs:line 125
   at Program.<Main>$(String[] args) in C:\Users\gc3ad\source\repos\RainLispConsole\RainLispConsole\Program.cs:line 72
```

**Comment by BDisp** [comment]
I have Windows 11 and I can't reproduce the issue, but others with Windows 10 already reported this.

**Comment by tznind** [comment]
See also #2714 it is proving difficult to fix :/

**Comment by chr1st0scli** [comment]
Should I close this or leave it if it has some value?

**Comment by tig** [comment]
No longer repo. Closing
