### ISSUE TITLE
Slider crashes with 'DiveByZero' exception when only 1 Option

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3099]
**Describe the bug**

When creating a `Slider<T>` and specifying only one option there is a hard crash at render time.

The bad code is:

```csharp
var min = (size - max_legend) / (_options.Count - 1);
```

```
System.DivideByZeroException
  HResult=0x80020012
  Message=Attempted to divide by zero.
  Source=Terminal.Gui
  StackTrace:
   at Terminal.Gui.Slider`1.CalcSpacingConfig() in /home/runner/work/Terminal.Gui/Terminal.Gui/Terminal.Gui/Views/Slider.cs:line 738
   at Terminal.Gui.Slider`1.set_Options(List`1 value) in /home/runner/work/Terminal.Gui/Terminal.Gui/Terminal.Gui/Views/Slider.cs:line 561
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64
```

**To Reproduce**
1. Create slider
2. Add a single Option
3. See error

**Comment by tig** [comment]
Did this get fixed with the new constructor PR?

**Comment by tznind** [comment]
No, I haven't looked into this yet.

**Comment by tig** [comment]
Got it...

```cs
	[Fact]
	void One_Option_Throws ()
	{
		// Arrange
		var slider = new Slider<int> ();
		slider.BeginInit ();
		slider.EndInit ();
		// Act/Assert
		Assert.Throws<NullReferenceException> (() => slider.Options = new List<SliderOption<int>> { new SliderOption<int> () });

	}
```
