### ISSUE TITLE
Shortcut crashes when removed from SuperView and ColorScheme set to null

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3664]
**Describe the bug**
Manifests in TGD when trying to delete a Shortcut

![image](https://github.com/user-attachments/assets/e78476b3-5272-4cda-ae4f-a7666d6bf660)

```
Error
Value cannot be null. (Parameter 'scheme')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String param
Name)
   at Terminal.Gui.ColorScheme..ctor(ColorScheme scheme)
   at Terminal.Gui.Shortcut.SetColors()
   at Terminal.Gui.Shortcut.set_ColorScheme(ColorScheme value)
   at TerminalGuiDesigner.SelectionManager.Clear(Boolean respectLock) in D:\
Repos\TerminalGuiDesigner\src\SelectionManager.cs:line 105
   at TerminalGuiDesigner.Operations.DeleteViewOperation.DoImpl() in D:\Rep
...
```

**To Reproduce**
1. Add a Shortcut to view area
2. Select it with rectangle selection
3. Press Delete

**Expected behavior**
SetColors should handle this situation

Basically more null handling in SetColors please such that if base.ColorScheme is null it doesn't bomb

**Comment by tig** [comment]
@tznind when you file bugs, can you please set the label, project, and milestone so I don't have to do it?
